{
 "title": "AWS Infra Monitoring - EBS",
 "description": "Visualize Amazon EBS metrics",
 "tags": [
  "Amazon",
  "AWS",
  "CloudWatch",
  "EBS"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Data_Source", "label": "Data source", "query": "cloudwatch" },
   { "name": "Region", "label": "Region", "query": "regions()" },
   { "name": "Period", "label": "Period [sec]", "query": "60,300,3600" },
   {
    "name": "Instance_IP",
    "query": "ec2_instance_attribute($Region, PrivateIpAddress, {})"
   },
   {
    "name": "Instance_Id",
    "query": "ec2_instance_attribute($Region, InstanceId, {\"private-ip-address\": [\"$Instance_IP\"]})"
   },
   {
    "name": "Volume_Id",
    "query": "ebs_volume_ids($Region, $Instance_Id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "VolumeId": "$Volume_Id" },
     "metricName": "VolumeTotalReadTime",
     "namespace": "AWS/EBS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "VolumeId": "$Volume_Id" },
     "metricName": "VolumeReadOps",
     "namespace": "AWS/EBS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "VolumeId": "$Volume_Id" },
     "metricName": "VolumeTotalWriteTime",
     "namespace": "AWS/EBS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "VolumeId": "$Volume_Id" },
     "metricName": "VolumeWriteOps",
     "namespace": "AWS/EBS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "EBS Brust Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "VolumeId": "$Volume_Id" },
     "metricName": "BurstBalance",
     "namespace": "AWS/EBS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}